export enum StatusPedido {
  PAGAMENTO_PENDENTE = 'PAGAMENTO_PENDENTE',
  PAGO = 'PAGO',
  EM_PREPARACAO = 'EM_PREPARACAO',
  AGUARDANDO_ENTREGADOR = 'AGUARDANDO_ENTREGADOR',
  ENTREGUE = 'ENTREGUE',
  CANCELADO = 'CANCELADO',
}
