export const STATUS_PEDIDO = {
  PAGAMENTO_PENDENTE: 'PAGAMENTO_PENDENTE',
  PAGO: 'PAGO',
  EM_PREPARACAO: 'EM_PREPARACAO',
  AGUARDANDO_ENTREGADOR: 'AGUARDANDO_ENTREGADOR',
  ENTREGUE: 'ENTREGUE',
  CANCELADO: 'CANCELADO'
} as const;

export type StatusPedido = typeof STATUS_PEDIDO[keyof typeof STATUS_PEDIDO];

export const STATUS_PEDIDO_ARRAY = Object.values(STATUS_PEDIDO);
